name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build and Verify
        run: mvn --no-transfer-progress --batch-mode -Dcheckstyle.skip -Dspotless.check.skip -Dlicense.skip=true verify
      - name: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: maven
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: package/target/openmessaging-benchmark-${{steps.release.outputs.major}}.${{steps.release.outputs.minor}}.${{steps.release.outputs.patch}}.tar.gz
        if: ${{ steps.release.outputs.release_created }}
